version: '3.8'

services:
  app:
    build: .
    image: spring-boot-app:1.0.0
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/crud_db;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ./data:/data
    restart: unless-stopped
